---
SubmitDate: 报账时间
DepartDate: 发车日期
CarLine: 路线
CarLineType: 路线类型
Payer: 结算方
CarID: 车牌
CarType: 车型
Mileage: 里程
Times: 趟数
OilWear: 油耗
OilPrice: 油价
OilSelfCosts: 油费成本
OilRefuelNumber: 加油量/公升
OilStationPrice: 加油站油价
OilStationCosts: 加油站加油金额
ReturnMoney: 油费返现金额
TransitHighwayCashCosts: 现金过境费
TransitHighwayETCCosts: ETC过境费
RepairCashCosts: 实报实修修理费
RepairDepreciationRate: 修理费返现比例
RepairDepreciationCosts: 修理费返现
Maintain: 保养费用
Material: 材料费用
Fine: 罚款
FreightCode: 货运编号 封铅
CarAndGoodsWeight: 总重
CarOnlyWeight: 皮重
GoodsWeight: 净重
RentCosts: 租外面的车
Other: 其他
Remark: 备注
Total: 总计
ResultForOilReturnCash: 返现总金额
